### ISSUE TITLE
java.lang.NumberFormatException

### ISSUE THREAD

**Issue by ArrowFX** [symt/BazaarNotifier#107]
[crash-2023-12-14_18.28.33-client.txt](https://github.com/symt/BazaarNotifier/files/13676468/crash-2023-12-14_18.28.33-client.txt)

**Comment by Cheezer1656** [comment]
I'm pretty sure that's happening because the Notification Module doesn't have any code to handle an order with an expiring message. I'll try to fix it later.

Relevant code:
```java
String ppu = lore.get(3).equals("") ? lore.get(4) : lore.get(5);
ppu = ppu.toLowerCase().replace("price per unit: ", "").replace(" coins", "")
    .replaceAll(",", "");

if (!ppu.contains("expired!")) {

  double pricePerUnit = Double.parseDouble(ppu);
```

**Comment by symt** [comment]
https://github.com/symt/BazaarNotifier/blob/80b219e855523fc210b0af15a4a8640a4583f74a/src/main/java/dev/meyi/bn/modules/module/NotificationModule.java#L204

I think this is already fixed in beta - you can join the discord server and download that version if needed, or compile from the source.
