### ISSUE TITLE
Keep showing trades that is already done in outdated/date tab

### ISSUE THREAD

**Issue by Lakkkiy** [symt/BazaarNotifier#26]
![image](https://user-images.githubusercontent.com/74483879/99178334-c143a180-271a-11eb-830b-9b167619a3c9.png)
After reloading the /bn reset and /bn bump nothing changes. Sometimes despairing.

**Comment by symt** [comment]
Sorry for the super late response. 

I'm aware of this and am going to add a fix when i get the chance

**Comment by symt** [comment]
Update: Hopefully this newest change fixes this by accident. `/bn reset orders` now works so it shouldn't be a problem.

Open another issue if it persists.
