### ISSUE TITLE
cant open mod?

### ISSUE THREAD

**Issue by conner4141** [symt/BazaarNotifier#27]
every time i try using the command /bn api then my api code it says its not right im not sure what to do

**Comment by symt** [comment]
Is your api key blacklisted? Do you have another mod that constantly grabs the api key?

Those are the only two things that would cause that to happen.

**Comment by symt** [comment]
API key is being disabled entirely so it is no longer necessary. I'll revisit this if hypixel requires the api again for bazaar requests.
