### ISSUE TITLE
Add item

### ISSUE THREAD

**Issue by gepbird** [symt/BazaarNotifier#48]
Enchanted carrot on a stick item is not recognized by the mod. Hypixel's bazaar API gives you ENCHANTED_CARROT_ON_A_STICK item which has 0 value, so use the correct ENCHANTED_CARROT_STICK id.

**Comment by symt** [comment]
If I recall correctly, ENCHANTED_CARROT_ON_A_STICK is actually a legacy item. Regardless, I'll update the conversions in the next mod version

Thank you.
