### ISSUE TITLE
Strange symbol instead of ","

### ISSUE THREAD

**Issue by WaromiV** [symt/BazaarNotifier#50]
![javaw_DJwahXszNu](https://user-images.githubusercontent.com/59875489/132093272-68256145-b555-44f4-b5d2-8f3f0826505f.png)

**Comment by WaromiV** [comment]
@symt please update discord link

**Comment by ghost** [comment]
@Noob-A https://discord.gg/ks9eVPEcQK
Is this issue persistent with other items?

**Comment by WaromiV** [comment]
> @Noob-A https://discord.gg/ks9eVPEcQK
> Is this issue persistent with other items?

Yes.

**Comment by ghost** [comment]
Join the discord and create a ticket in #support, I'll try to help

**Comment by symt** [comment]
This is probably a system language issue and isn't worth the trouble to fix at the moment.
