### ISSUE TITLE
Game Crashing 2 times and one bluescreen

### ISSUE THREAD

**Issue by DeParty93** [symt/BazaarNotifier#59]
Game Crashing 2 times and one bluescreen after updating to 1.4.7. after downgrading to 1.4.6 it works just fine.

**Comment by symt** [comment]
Any chance you have some logs for this? 

`.minecraft/logs/latest.log` following a crash.

This is really strange because the only change was to the bazaar conversions file.

**Comment by DeParty93** [comment]
i retryed  today now it works. I'll post the logs if it happens again. but at the moment it works just fine. idk wat the issue was last time...

**Comment by symt** [comment]
Reopen if it shows up
