### ISSUE TITLE
Waiting for bazaar data

### ISSUE THREAD

**Issue by gustas4848** [symt/BazaarNotifier#67]
I dont see nothing it just says "Waiting for bazaar data"
![image](https://user-images.githubusercontent.com/104920606/166724109-d89be84b-1468-48ee-9414-0ba3149bfecb.png)

**Comment by wawadanon** [comment]
happens to me too

**Comment by symt** [comment]
This is an issue with hypixel's SSL certificate and Minecraft's java version. I'm currently looking for a permanent fix, but until then, if you change the java executable that your game uses it'll work.

**Comment by symt** [comment]
Fixed in #70
