### ISSUE TITLE
Easy Search for Bazaar

### ISSUE THREAD

**Issue by wawadanon** [symt/BazaarNotifier#68]
there are a lot of bazaar items and some   I don't know where they are and a search option would help

**Comment by symt** [comment]
Do you think something like a search bar like directly above the item list that shows suggested flips or something that allows you to quickly find items in the bazaar?


I could see it being a mix of both or having some sort of sorting module that highlights which categories you'd need to go to for finding specific items.

**Comment by wawadanon** [comment]
yeah especially with the new power stones and reforge stones it hard to find the item so it would help a lot

**Comment by symt** [comment]
This is now redundant with the introduction of the search feature in the bazaar
