### ISSUE TITLE
Offer window not displaying correctly

### ISSUE THREAD

**Issue by Ghoslain** [symt/BazaarNotifier#89]
Sometimes (often) orders dissapear, and canceling one cancels another that is not related to it (idk if thats correct but at list it dissapears from display). The list isn't empty since it doens't show the "no orders" window, but it shows a little black bar on the left

**Comment by symt** [comment]
On beta or 1.4.12?

**Comment by Ghoslain** [comment]
Beta "1.5.0-beta8"

**Comment by symt** [comment]
With beta 14 and 15, this shouldn't be an issue anymore, but if it is, make another issue or go to the discord server and report it.
