### ISSUE TITLE
Suggestion - Enhancement

### ISSUE THREAD

**Issue by Ghoslain** [symt/BazaarNotifier#90]
Add the same setting as for suggester window & crafting window but for the Orders window (eg, having 21/27 displayed instead of 10)

**Comment by symt** [comment]
I think we can probably do that. At least now you should be able to scroll down through the list.

**Comment by Ghoslain** [comment]
Yeah its decent but having the numbers and stuff should be easier to have tracking of the items, since you did the same for the 2 other windows its just copy pasting stuff I suppose

**Comment by symt** [comment]
Done in #96
