### ISSUE TITLE
Crashing every so often when right clicking Crafting Module

### ISSUE THREAD

**Issue by XenoStone1009** [symt/BazaarNotifier#91]
Expected behavior: Right click to change tab between Instant Sell, Sell Offer, and Instant (1m)

Actual behavior: Right clicking the tab, especially when the module fails to load like this https://i.imgur.com/QK4uID3.png

Mod list and their versions: https://i.imgur.com/RPwK0H1.png

Log: https://hastebin.com/ugipimujeq

**Comment by symt** [comment]
Sorry for the late response. If this is still an issue, make a new issue
